### ISSUE TITLE
PxLoader on NPM

### ISSUE THREAD

**Issue by vdaguenet** [thinkpixellab/PxLoader#34]
Hi!

I really like PxLoader and I use it on every project I do. But I would like to install the library with NPM instead of Bower. Is it possible to do this ? :)

**Comment by joelfillmore** [comment]
Yes, its definitely possible. If you'd like to tackle any changes we need to make, I'd be happy to review the pull request.

**Comment by joelfillmore** [comment]
Working now, thanks!
npm install pxloader
