### ISSUE TITLE
Numbers should not jump in "addProgressListener ". For eg. -  10, 11, 12, 13 ... instead of 10, 12, 15, 20.

### ISSUE THREAD

**Issue by prashantsani** [thinkpixellab/PxLoader#38]
hello!
Great plugin, have been using the same for couple of my websites.

Our client has a requirement that can we have the plugin output the numbers in "addProgressListener " in a smooth transition 
For example - 
10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 ... instead of 10, 12, 15, 20.

Not sure if its possible with adding a variable and using setTimeout,etc. But that would be too complicated.

Thanks.

**Comment by dinonondi** [comment]
Would love that feature aswell! Is it easy to add ?
