### ISSUE TITLE
PxLoaderImage throws exception when options is undefined

### ISSUE THREAD

**Issue by srveit** [thinkpixellab/PxLoader#58]
This code used to work:

```
pxImage = new PxLoaderImage(src);
```

It now throws an exception as of version 1.1.1:

```
PxLoaderImage.js:24 Uncaught TypeError: Cannot read property 'origin' of undefined
```

A workaround is to pass in an empty options object:

```
pxImage = new PxLoaderImage(src, undefined, undefined, {});
```

**Comment by joelfillmore** [comment]
Duplicate of #58, should be fixed in v1.1.2

**Comment by joelfillmore** [comment]
@srveit - just realized that I had pushed v1.1.2 to GitHub but hadn't published to npm. Sorry, my mistake! Do an npm update and it should work now.

**Comment by srveit** [comment]
@joelfillmore Thanks!
